var express = require('express');
var router = express.Router();
const userController = require('../controllers/user');
const isAuth = require('../middleware/check-auth');

router.post('/create', userController.createUser);
router.post('/signin', userController.signInUser);
router.post('/update/:id', userController.updateUser);
 router.post('/updatepassword/:id' , userController.updatePassword);
 router.post('/resetpassword/:id' , userController.resetPassword);
 router.post('/mailsend' , userController.resetpassword_usingmail);
 router.get('/getbyId/:id' , userController.getbyId);
 router.get('/getall' , userController.getAll);
 router.post('/follow/:followerId/:followingId' , userController.follow);
 router.post('/unfollow/:followerId/:followingId' , userController.unfollow);
 router.post('/friendrequest/:userId/:friendId' , userController.friendRequest);
 router.post('/cancelfriendrequest/:userId/:friendId' , userController.cancelFriendRequest);
 router.post('/unfriend/:userId/:friendId' , userController.unFriend);
 router.post('/confirmfriendship/:userId/:friendId' , userController.confirmFriendship);
 router.get('/checkfriendshipstatus/:userId/:friendId' , userController.checkFriendshipStatus);
 router.get('/getbyId/:id' , userController.getById);
 router.get('/getfollowers/:userid' , userController.getFollowers);  
 router.get('/getfollowings/:userid' , userController.getFollowings); 
 router.get('/isfollower/:userid/:followerId' , userController.isfollower); 
 router.get('/isfollowing/:userid/:followingId' , userController.isfollowing); 
 router.get('/getallfriendrequests/:userId' , userController.getAllFriendRequests); 
 router.get('/getallfriends/:userId' , userController.getAllFriends);
 router.get('/getallconversationsbyuser/:userId' , userController.getAllConversationsByUser); 
 router.post('/changeblockstatus/:userId' , userController.changeBlockStatus); 

module.exports = router;
